vru_node:
  ros__parameters:
    # 串口设备路径
    port: "/dev/ttyUSB0"
    # 波特率（默认 115200）
    baud: 115200
    # ROS frame_id
    frame_id: "vru"
    # 加速度量程：0=±2g  1=±4g  2=±8g  3=±16g
    accel_range: 0
    # 角速度量程：0=±250dps  1=±500dps  2=±1000dps  3=±2000dps
    gyro_range: 0
